name: Scheduled Merge

on:
  schedule:
    - cron: "*/5 * * * *"  # Ejecutar cada 5 minutos

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "GlendyT"
          git config --global user.email "glendytuyuc@gmail.com"

      - name: Check if branch exists
        id: check_branch
        run: |
          BRANCH_NAME="11novtest"
          if git ls-remote --heads origin "$BRANCH_NAME" | grep "$BRANCH_NAME"; then
            echo "branch_exists=true" >> $GITHUB_ENV
          else
            echo "branch_exists=false" >> $GITHUB_ENV
          fi

      - name: Create Pull Request
        if: env.branch_exists == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.AUTO_TOKEN }}
          base: main  # Rama base donde quieres hacer el merge
          branch: 11novtest  # La rama que quieres fusionar
          title: "Auto-merge 11novtest into main"
          body: "This pull request was created automatically by GitHub Actions."

      - name: Auto-Merge Pull Request
        if: env.branch_exists == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.AUTO_TOKEN }}
          script: |
            const pr = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: "11novtest",
              base: "main",
              state: "open"
            });
            if (pr.data.length > 0) {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.data[0].number,
                merge_method: "merge"
              });
              console.log("Pull request merged successfully.");
            } else {
              console.log("No open pull request found to merge.");
            }
