name: Scheduled Merge

on:
  schedule:
    - cron: '0 10 * * 1-5' # Lunes a Viernes a las 10 AM UTC

jobs:
  merge_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

    #   - name: Configure Git
    #     run: |
    #       git config --global user.name "GlendyT"
    #       git config --global user.email "glendytuyuc@gmail.com"

    #   - name: Find Branch to Merge
    #     id: find_branch
    #     run: |
    #       # Lista todas las ramas que cumplen con un patrón y toma la primera
    #       BRANCH=$(git branch -r | grep -E 'origin/feature-*' | head -n 1 | sed 's/origin\///')
    #       echo "branch_to_merge=$BRANCH" >> $GITHUB_ENV

    #   - name: Merge branch
    #     env:
    #       TARGET_BRANCH: 'main' # Rama destino
    #     run: |
    #       git checkout ${{ env.TARGET_BRANCH }}
    #       git pull origin ${{ env.TARGET_BRANCH }}
    #       git merge origin/${{ env.branch_to_merge }}
    #       git push origin ${{ env.TARGET_BRANCH }}
